// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcemvfoydpuzbdqxajnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZW12Zm95ZHB1emJkcXhham5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTE5MTcsImV4cCI6MjA2MjA2NzkxN30.sUQpILOFoOp-NqbR_ZuMNzeggGrQL7HGIaxntaIMjLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);